#!/usr/bin/env bash
set -e

echo "=== Running Python script ==="
python3 ./img2txt.py "$@"

# Check if CSV was actually created before starting Node
if [ ! -f "resources/csv/bin_collection_dates.csv" ]; then
    echo "❌ Error: CSV file was not generated by img2txt.py"
    exit 1
fi

echo -e "\n=== Running WhatsApp Scheduler ==="
cd whatsapp-scheduler
node index.js
